title: "Talamante Morais – Advocacia Pública Municipal"
email: "talamantemorais@gmail.com"
description: "Site do escritório de advocacia pública municipal"
baseurl: ""
url: "https://talamante-adv.github.io"
github_username: "talamante-adv"
markdown: kramdown
google_analytics: G-ZKCPTG7K1T
theme: minima
plugins:
  - jekyll-feed
